# Generated by Django 5.1.3 on 2024-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servicos_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='protocolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
