# Generated by Django 5.1.3 on 2024-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servicos_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
